const apiConstants = {
  // Check is user logged in or not
  CHECK_IS_USER_LOGGED_IN: "CHECK_IS_USER_LOGGED_IN",
  CHECK_IS_USER_LOGGED_IN_SUCCESS: "CHECK_IS_USER_LOGGED_IN_SUCCESS",
  CHECK_IS_USER_LOGGED_IN_FAIL: "CHECK_IS_USER_LOGGED_IN_FAIL",

  // Login User
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  // Register User
  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
};

export default apiConstants;
